spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9000/realms/web-ecommerce"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/api/v1/sale/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222
  max-http-request-header-size: 16384